# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-9764-esp-station-thomas/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcvu9p-flga2577-3-e

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/xpm_cdc.sv
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/xpm_fifo.sv
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/xpm_memory.sv
    }
      rt::read_verilog {
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Deparser_t.HDL/Deparser_t.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Deparser_t.HDL/Deparser_t.vp
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Forward_t.HDL/Forward_t.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Forward_t.HDL/Forward_t.vp
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Parser_t.HDL/Parser_t.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/Parser_t.HDL/Parser_t.vp
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_PROTOCOL_ADAPTERs.HDL/S_PROTOCOL_ADAPTER_EGRESS.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_PROTOCOL_ADAPTERs.HDL/S_PROTOCOL_ADAPTER_INGRESS.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_RESETTER.HDL/S_RESETTER_line.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/S_SYNCER_for_Deparser.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/S_SYNCER_for_S_SYNCER_for_Deparser.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/S_SYNCERs.HDL/S_SYNCER_for__OUT_.v
      /home/thomas/Documents/p4_fpga_plugin/rtl/t0.P4.HDL/XilinxSwitch/XilinxSwitch_vivado/XilinxSwitch/XilinxSwitch.srcs/sources_1/imports/XilinxSwitch/XilinxSwitch.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-9764-esp-station-thomas/realtime/XilinxSwitch_synth.xdc
    rt::sdcChecksum
    set rt::top XilinxSwitch
    rt::set_parameter enableIncremental true
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-9764-esp-station-thomas/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
